### ISSUE TITLE
Error en bash windows 10

### ISSUE THREAD

**Issue by Oxicode** [zerobyte-id-bak/Bashter#1]
![image](https://user-images.githubusercontent.com/1320709/57143565-c1708c00-6d84-11e9-8698-98218675a05a.png)

![image](https://user-images.githubusercontent.com/1320709/57143526-aaca3500-6d84-11e9-92a7-aeade869cafb.png)

**Comment by zerobyte-id-bak** [comment]
U can using `dos2unix` or command below:
```sed -i 's/\r$//' *.bash```
